# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'Контекстно-системная философия'
author = f'соавторы проекта {project}'
copyright = f'2020, {author}.'
release = '0.1dev1'
version = f'{release}'
html_title = f'{project}. Издание {release}'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'rst2pdf.pdfbuilder',
    'sphinx.ext.imgconverter',
]

# Сохранение прозрачного фона .svg изображений при конвертации в .png,
# найдено в документации к команде convert утилиты ImageMagick.
image_converter_args = ['-background', 'transparent']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'ru'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'README.rst', 'Thumbs.db', '.DS_Store', '.venv']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Для сборки на Read the Docs
master_doc = 'index'

# Дата
today_fmt = '%d %B %Y года'

# PDF
pdf_documents = [(
    master_doc,
    project,
    project,
    author,
)]
pdf_stylesheets = ['sphinx', 'kerning', 'a4']

# LaTeX
latex_documents = [(
    master_doc,
    f'{project}.tex'.replace(' ', '_'),
    project,
    author,
    'manual',  # documentclass
)]

latex_elements = {
    'releasename': 'Издание',
}

